name: 'Steam Deploy'
description: 'Deploy to Steam using SteamCMD without Docker'
author: 'neptaco'

inputs:
  username:
    description: 'The Steam username'
    required: true
  configVdf:
    description: 'The contents of the Steam config.vdf file'
    required: true
  appId:
    description: 'The Steam App ID'
    required: true
  buildDescription:
    description: 'The build description'
    required: false
    default: ''
  rootPath:
    description: 'The root path of the build files'
    required: false
    default: '.'
  vdfPath:
    description: 'The path to the VDF file'
    required: false
    default: ''
  depot1Id:
    description: 'The Depot ID for depot 1'
    required: false
    default: ''
  depot1Path:
    description: 'The path for depot 1'
    required: false
    default: ''
  depot2Id:
    description: 'The Depot ID for depot 2'
    required: false
    default: ''
  depot2Path:
    description: 'The path for depot 2'
    required: false
    default: ''
  depot3Id:
    description: 'The Depot ID for depot 3'
    required: false
    default: ''
  depot3Path:
    description: 'The path for depot 3'
    required: false
    default: ''
  depot4Id:
    description: 'The Depot ID for depot 4'
    required: false
    default: ''
  depot4Path:
    description: 'The path for depot 4'
    required: false
    default: ''
  depot5Id:
    description: 'The Depot ID for depot 5'
    required: false
    default: ''
  depot5Path:
    description: 'The path for depot 5'
    required: false
    default: ''
  depot6Id:
    description: 'The Depot ID for depot 6'
    required: false
    default: ''
  depot6Path:
    description: 'The path for depot 6'
    required: false
    default: ''
  depot7Id:
    description: 'The Depot ID for depot 7'
    required: false
    default: ''
  depot7Path:
    description: 'The path for depot 7'
    required: false
    default: ''
  depot8Id:
    description: 'The Depot ID for depot 8'
    required: false
    default: ''
  depot8Path:
    description: 'The path for depot 8'
    required: false
    default: ''
  depot9Id:
    description: 'The Depot ID for depot 9'
    required: false
    default: ''
  depot9Path:
    description: 'The path for depot 9'
    required: false
    default: ''
  releaseBranch:
    description: 'The branch to release to (e.g., prerelease, beta, default)'
    required: false
    default: ''
  debugBranch:
    description: 'Set to true to include debug files (*.pdb, BurstDebugInformation, etc.)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup and Deploy
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/deploy.sh
      env:
        STEAM_USERNAME: ${{ inputs.username }}
        STEAM_CONFIG_VDF: ${{ inputs.configVdf }}
        STEAM_APP_ID: ${{ inputs.appId }}
        BUILD_DESCRIPTION: ${{ inputs.buildDescription }}
        ROOT_PATH: ${{ inputs.rootPath }}
        VDF_PATH: ${{ inputs.vdfPath }}
        DEPOT1_ID: ${{ inputs.depot1Id }}
        DEPOT1_PATH: ${{ inputs.depot1Path }}
        DEPOT2_ID: ${{ inputs.depot2Id }}
        DEPOT2_PATH: ${{ inputs.depot2Path }}
        DEPOT3_ID: ${{ inputs.depot3Id }}
        DEPOT3_PATH: ${{ inputs.depot3Path }}
        DEPOT4_ID: ${{ inputs.depot4Id }}
        DEPOT4_PATH: ${{ inputs.depot4Path }}
        DEPOT5_ID: ${{ inputs.depot5Id }}
        DEPOT5_PATH: ${{ inputs.depot5Path }}
        DEPOT6_ID: ${{ inputs.depot6Id }}
        DEPOT6_PATH: ${{ inputs.depot6Path }}
        DEPOT7_ID: ${{ inputs.depot7Id }}
        DEPOT7_PATH: ${{ inputs.depot7Path }}
        DEPOT8_ID: ${{ inputs.depot8Id }}
        DEPOT8_PATH: ${{ inputs.depot8Path }}
        DEPOT9_ID: ${{ inputs.depot9Id }}
        DEPOT9_PATH: ${{ inputs.depot9Path }}
        RELEASE_BRANCH: ${{ inputs.releaseBranch }}
        DEBUG_BRANCH: ${{ inputs.debugBranch }}

branding:
  icon: 'upload-cloud'
  color: 'blue'